#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=95
boot() {
	mount_root done
	rm -f /sysupgrade.tgz

	# process user commands
	[ -f /etc/rc.local ] && {
		sh /etc/rc.local
	}

	# set leds to normal state
	. /etc/diag.sh
	set_state done

	# start testnet
	/sbin/testnet &

	# trigger a fake hotplug net event
	# to simulte the plug in/out of wan cable
	# that might have happened while the router was powered off
	/sbin/netmode-repeater-correction
}
