#!/bin/sh /etc/rc.common

. /lib/functions/iop_macro.sh

START=10
USE_PROCD=1
EXTRA_COMMANDS="macro"
EXTRA_HELP="        macro   convert options to macro"

handle_threads()
{
	# initialize kernel schedule priorities
	smd -s
}

handle_passwords()
{
	local users="admin support user"
	local user ppwd spwd

	for user in $users; do
		ppwd=$(sed -ne "/^$user:/s/^$user:\([^:]*\):.*$/\1/p" /etc/passwd)
		spwd=$(sed -ne "/^$user:/s/^$user:\([^:]*\):.*$/\1/p" /etc/shadow)

		if [ -n "${ppwd#[\!x]}" ] && [ -z "${spwd#[\!x]}" ]; then
			logger -t migrate-shadow "Moving $user password hash into shadow database"
			grep -wq $user /etc/shadow || echo "$user:*:0:0:99999:7:::" >>/etc/shadow
			sed -i -e "s:^$user\:[^\:]*\::$user\:x\::"     /etc/passwd
			sed -i -e "s:^$user\:[^\:]*\::$user\:$ppwd\::" /etc/shadow
		fi
	done
}

handle_upgrade_count() {
	if cat /proc/cmdline |grep -q "ubi:rootfs_0"; then
		brcm_fw_tool -s -1 update /dev/mtd0
	elif cat /proc/cmdline |grep -q "ubi:rootfs_1"; then
		brcm_fw_tool -s -1 update /dev/mtd1
	else
		ls /cferam* | awk -F'.' '{print$NF}'
	fi
}

handle_openwrtversion() {
	## THIS WILL NEED TO BE MOVED TO THE RIGHT PLACE
	# even though this runs repeatedly, it does not matter 

	# write iop version data to /etc/openwrt_version from where procd 
	# will read it and display it using system info ubus call
	IOP_VERSION="$(db get hw.board.iopVersion)"
	RELEASE=${IOP_VERSION%-*}; RELEASE=${RELEASE##*_}
	REVISION=${IOP_VERSION##*-}
	MODEL=$(db get hw.board.routerModel)
	HARDWARE=$(db get hw.board.hardware)

	sed -i "s/.*DISTRIB_ID.*/DISTRIB_ID='IOPSYS'/g" /etc/openwrt_release
	sed -i "s/.*DISTRIB_RELEASE.*/DISTRIB_RELEASE='$RELEASE'/g" /etc/openwrt_release
	sed -i "s/.*DISTRIB_REVISION.*/DISTRIB_REVISION='$REVISION'/g" /etc/openwrt_release
	sed -i "s/.*DISTRIB_DESCRIPTION.*/DISTRIB_DESCRIPTION='IOPSYS $REVISION $RELEASE'/g" /etc/openwrt_release
	sed -i "s/.*DISTRIB_TARGET.*/DISTRIB_TARGET='$MODEL'/g" /etc/openwrt_release

	sed -i "s/.*DEVICE_MANUFACTURER.*/DEVICE_MANUFACTURER='INTENO'/g" /etc/device_info
	sed -i "s/.*DEVICE_PRODUCT.*/DEVICE_PRODUCT='$HARDWARE'/g" /etc/device_info
	sed -i "s/.*DEVICE_REVISION.*/DEVICE_REVISION='$MODEL'/g" /etc/device_info

	# openwrt defaults are set like this
	# DISTRIB_ID='OpenWrt'
	# DISTRIB_RELEASE='15.05'
	# DISTRIB_REVISION='r47165'
	# DISTRIB_CODENAME='chaos_calmer'
	# DISTRIB_TARGET='bcm53xx/generic'
	# DISTRIB_DESCRIPTION='OpenWrt Chaos Calmer 15.05'
	# DISTRIB_TAINTS='no-all busybox'

	# the template looks like this
	# DISTRIB_ID="%D"
	# DISTRIB_RELEASE="%C"
	# DISTRIB_REVISION="%R"
	# DISTRIB_CODENAME="%n"
	# DISTRIB_TARGET="%S"
	# DISTRIB_DESCRIPTION="%D %N %V"
	# DISTRIB_TAINTS="%t"
}

handle_backup() {
	local ISTHERE=0

	compare_with() {
		local confile="$2"
		config_get files "$1" file
		for f in $files; do
			if [ "$f" == "$confile" ]; then
				ISTHERE=1
				return 0
			fi
		done
	}

	config_load backup

	for conf in $(ls /etc/config); do
		case $conf in
			backup|boardpanel|dmmap|fstab|hosts|luci|rpcd|speedtest|voice_codecs) continue;
		esac
		config_foreach compare_with service "/etc/config/$conf"
		if [ $ISTHERE -eq 0 ]; then
			uci set backup.$conf=service
			uci set backup.$conf.desc=$conf
			uci set backup.$conf.file="/etc/config/$conf"
		fi
		ISTHERE=0
	done

	uci commit backup

}

print_out_sw_ver() {
	echo Software Version: $(grep "IOP Version" /etc/banner | awk '{print$3}') >/dev/kmsg
}

boot() {
	print_out_sw_ver
	handle_upgrade_count
	handle_threads
	handle_openwrtversion
	handle_passwords
	handle_backup
	iop_config_from_macro
}

start_service() {
	iop_config_from_macro
}

