#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
NAME=otherbank

this_file=/tmp/this_bank_iopver
other_file=/tmp/other_bank_iopver
other_mnt=/tmp/other_mnt

awk '/IOP Version:/ {print $3}' /etc/banner > $this_file
echo "WAIT" > $other_file

start_service () {

(
	sleep 15s

	grep -q rootfs_0 /proc/cmdline && otherbank=rootfs_1 || otherbank=rootfs_0
	mkdir $other_mnt

	if ! mount -t ubifs -o ro ubi:${otherbank} ${other_mnt} ; then
		echo "FAIL" > $other_file
		exit 0
	fi

	other_verstr=$(awk '/IOP Version:/ {print $3}' ${other_mnt}/etc/banner)
	umount $other_mnt
	rmdir $other_mnt

	echo "$other_verstr" > $other_file
) &

}
