#!/bin/sh /etc/rc.common

START=12
USE_PROCD=1

migrate_shadow() {
	/bin/sh /rom/etc/uci-defaults/10_migrate-shadow
}

set_password() {
        local usertype="$1"
        local password
	config_get password $usertype password

	[ -n "$password" ] && (echo $password; sleep 1; echo $password) | passwd $usertype >/dev/null 2>&1

	uci delete passwords.$usertype.password >/dev/null 2>&1
}

maybe_reset_password() {
	local usertype="$1"
	local reset
	config_load passwords
	config_get reset $usertype reset

	if [ "$reset" == "1" ]; then
		local pwd_config
		config_load /rom/etc/config/passwords
		config_get pwd_config $usertype password

		if [ -n "$pwd_config" ]; then
			(echo $pwd_config; sleep 1; echo $pwd_config) | passwd $usertype >/dev/null 2>&1
		else
			local pwd_shadow=$(sed -n "s/$usertype:\([^:]*\):.*$/\1/p" /rom/etc/shadow)
			sed -i -e "s:^$usertype\:[^\:]*\::$usertype\:$pwd_shadow\::" /etc/shadow

			local pwd_passwd=$(sed -n "s/$usertype:\([^:]*\):.*$/\1/p" /rom/etc/passwd)
			sed -i -e "s:^$usertype\:[^\:]*\::$usertype\:$pwd_passwd\::" /etc/passwd
		fi
		uci delete passwords.$usertype.reset >/dev/null 2>&1
	fi
}

service_triggers()
{
	procd_add_reload_trigger "passwords"
}

start_service() {
	migrate_shadow
	config_load passwords
	config_foreach set_password usertype
	config_foreach maybe_reset_password usertype
	uci commit passwords
}
