#! /bin/sh

# record that we are doing a manual reboot
# this to be able to detect a reboot done by watchdog

# if no reason then set manual
if [ ! -f /tmp/reboot_reason ]
then
   echo manual > /tmp/reboot_reason
fi

# First try the overlay this maight fail
cat /tmp/reboot_reason 2>/dev/null >/etc/reboot
if [ $? != 0 ]
then
    # overlayfs gave error probably a defaultreset try the main filesystem
    cat /tmp/reboot_reason 2>/dev/null >/rom/etc/reboot
fi

sync
/bin/busybox reboot $@

# if system do not reboot in 20 second force it anyway.
sleep 20
/bin/busybox reboot -f $@
