#!/bin/sh

# Print system info and logs

cat /etc/banner
date
cat /proc/cpuinfo
top -b -n 1
ubus call router.system info
ubus call router.network dump
ubus call router.network clients
ubus call router.network leases '{ "network": "lan" }'
cat /proc/net/arp
ifstatus lan
ifstatus wan
logread
dmesg
lsusb
lspci -k
lsmod
cat /proc/slabinfo
cat /etc/config/network
ifconfig
iptables-save
opkg list
db show | grep has[A-Z]
icwmpd -m 1 get_value InternetGatewayDevice.

