#!/bin/sh

#exec 2>/dev/null

. /lib/functions.sh
. /usr/share/libubox/jshn.sh

local _VIFNUM=0

RA="/etc/Wireless/RT2860/RT2860.dat"
RAI="/etc/Wireless/iNIC/iNIC_ap.dat"

CONFILE=""

remove_from_networks() {
	local iface=$1
	local ifname=""
	for net in $(uci show network | grep network.*.interface | awk -F'[.,=]' '{print$2}' | tr '\n' ' '); do
		ifname=""
		for ifc in $(uci -q get network.$net.ifname); do
			if [ "$ifc" != "$iface" ]; then
				ifname="$ifname $ifc"
			fi
		done
		uci -q set network.$net.ifname="$(echo $ifname | tr ' ' '\n' | sort -u | tr '\n' ' ' | sed 's/[ \t]*$//')"
		uci commit network
	done
	ifconfig $iface down
}

add_to_network() {
	local network=$1
	local iface=$2
	local ifname=""
	for net in $(uci show network | grep network.*.interface | awk -F'[.,=]' '{print$2}'); do
		ifname="$(uci -q get network.$net.ifname)"
		if [ "$net" == "$network" ]; then
			ifname="$ifname $iface"
		fi
		uci -q set network.$net.ifname="$(echo $ifname | tr ' ' '\n' | sort -u | tr '\n' ' ' | sed 's/[ \t]*$//')"
	done
	uci commit network
}

find_in_network() {
	local wcfg=$1
	local iface=$2
	uci -q delete wireless.$wcfg.network
	for net in $(uci show network | grep network.*.interface | awk -F'[.,=]' '{print$2}' | tr '\n' ' '); do
		for ifc in $(uci -q get network.$net.ifname); do
			if [ "$ifc" == "$iface" ]; then
				uci -q set wireless.$wcfg.network="$net"
			fi
		done
	done
}

vif_settings() {
	local cfg=$1
	local iface=$2
	local device ifname ssid encryption key cipher authmode

	find_in_network $cfg $iface

	remove_from_networks $iface

	config_get device $cfg device
	config_get ssid $cfg ssid ""
	config_get encryption $cfg encryption ""
	config_get key $cfg key ""

	authmode="OPEN"
	cipher="NONE"

	case "$encryption" in
		*psk*)
			authmode=WPAPSK
			cipher=AES
		;;
	esac

	case "$iface" in
		rai*)
			CONFILE=$RAI
		;;
		ra*)
			CONFILE=$RA
		;;
	esac

	VNO=$((_VIFNUM + 1 ))

	sed -i "s/AuthMode=.*/AuthMode=$authmode/g" $CONFILE
	sed -i "s/EncrypType=.*/EncrypType=$cipher/g" $CONFILE	

	sed -i "s/SSID$VNO=.*/SSID$VNO=$ssid/g" $CONFILE
	sed -i "s/WPAPSK$VNO=.*/WPAPSK$VNO=$key/g" $CONFILE


	config_get_bool disabled $cfg disabled 0
	if [ "$disabled" == "0" ]; then
		#config_get network $cfg network
		network="$(uci -q get wireless.$cfg.network)"
		[ -n "$network" ] && add_to_network $network $iface

		ifconfig $iface up
	fi
	
}

configure_vif() {
	local vif="$1"
	local device iface mbssmac mbssnum
	config_get device "$vif" device

	[ "$2" == "$device" ] || continue

	if [ $_VIFNUM -eq 0 ]; then
		iface="$device"
	else

		ln=$((${#device}-1))
		iface="${device:0:$ln}$_VIFNUM"
	fi

	# set wireless ifname in wireless config
	uci set wireless.$vif.ifname=$iface

	vif_settings $vif $iface

	_VIFNUM=$((_VIFNUM+1))
}

wdev_settings() {
	local cfg=$1
	local device=$cfg
	local country channel radio country_code disabled

	config_get_bool disabled $cfg disabled 0
	[ "$disabled" == "1" ] && radio=0 || radio=1
	config_get_bool radio $cfg radio $radio

	config_get country $cfg country "EU/13"
	config_get channel $cfg channel "auto"

	country_code=$(echo $country | awk -F'/' '{print$1}')
	country_rev=$(echo $country | awk -F'/' '{print$2}')

	case "$device" in
		rai*)
			CONFILE=$RAI
		;;
		ra*)
			CONFILE=$RA
		;;
	esac

	sed -i "s/RadioOn=.*/RadioOn=$radio/g" $CONFILE
	sed -i "s/Channel=.*/Channel=$channel/g" $CONFILE
	sed -i "s/CountryCode=.*/CountryCode=$country_code/g" $CONFILE
}

setup_wifi_device() {
	local device="$1"
	local vif

	# configure virtual wireless interfaces
	config_foreach configure_vif wifi-iface "$device"
	_VIFNUM=0

	wdev_settings $device
}

configure_wifi() {
	config_load wireless
	config_foreach setup_wifi_device wifi-device
	uci commit wireless
}

case "$_ACTION" in
	detect)
		exit
	;;
	disable|enable)
		exit
	;;
	clients)
		if [ -n "$2" ]; then
			ubus call router.wireless stas "{\"vif\":\"$2\"}"
		else
			ubus call router.wireless stas
		fi
		exit
	;;
	down|off)
		for idx in 0 1 2 3; do
			ifconfig ra$idx down
			ifconfig rai$idx down
		done
		exit
	;;
	import)
		exit
	;;
	toggle)
		exit
	;;
	reload|restart|up)
		_RELOAD=1
	;;
esac

#for idx in 0 1 2 3; do
#	remove_from_networks ra$idx
#	remove_from_networks rai$idx
#done

configure_wifi

# trigger network reload
ubus -t 5 call network reload
# re-populate network in questd
ubus -t 5 call router.network reload
